const DOCUMENT_UPLOAD_MAX_SIZE_BYTES = 50 * 1024 * 1024 * 1024;
const DOCUMENT_UPLOAD_MAX_SIZE_LABEL = "50GB";

module.exports = {
  DOCUMENT_UPLOAD_MAX_SIZE_BYTES,
  DOCUMENT_UPLOAD_MAX_SIZE_LABEL,
};
