const DOCUMENT_UPLOAD_MAX_SIZE_MB = 50;
const DOCUMENT_UPLOAD_MAX_SIZE_BYTES = DOCUMENT_UPLOAD_MAX_SIZE_MB * 1024 * 1024;
const DOCUMENT_UPLOAD_MAX_SIZE_LABEL = `${DOCUMENT_UPLOAD_MAX_SIZE_MB} MB`;

module.exports = {
  DOCUMENT_UPLOAD_MAX_SIZE_BYTES,
  DOCUMENT_UPLOAD_MAX_SIZE_LABEL,
  DOCUMENT_UPLOAD_MAX_SIZE_MB,
};
